export const genres = [
  "Romance",
  "Fantasia",
  "Ficção Científica",
  "Mistério",
  "Suspense",
  "Terror",
  "Drama",
  "Aventura",
  "Biografia",
  "Autobiografia",
  "Memórias",
  "Distopia",
  "Poesia",
  "Histórico",
  "Literatura Clássica",
  "Young Adult (YA)",
  "Infantil",
  "Autoajuda",
  "Humor",
  "Erótico",
  "Espiritualidade",
  "Religião",
  "Policial",
  "Cyberpunk",
  "Steampunk",
  "Fantasia Urbana",
  "Mitologia",
  "Contos",
  "Crônicas",
  "Clássico",
  "Realismo Mágico",
  "Literatura Infantil",
  "Romance Clássico",
  "Fantasia Histórica",
  "Não-ficção",
  "Ficção Histórica",
  "Filosofia",
  "Ficção",
  "Ficção Gótica",
];
