export const tropes = [
  "Enemies to Lovers",
  "Friends to Lovers",
  "Love Triangle",
  "Forbidden Love",
  "Second Chance",
  "Fake Relationship",
  "Slow Burn",
  "Grumpy x Sunshine",
  "Forced Proximity",
  "One Bed",
  "Secret Identity",
  "Hidden Royalty",
  "Found Family",
  "Revenge",
  "Amnesia",
  "Marriage of Convenience",
  "Age Gap",
  "Best Friend's Sibling",
  "Soulmates",
  "Opposites Attract",
  "Unrequited Love",
  "Workplace Romance",
  "Coming of Age",
  "Dark Secret",
  "Tragic Past",
  "Betrayal",
  "Chosen One",
  "Hero's Journey",
  "Rags to Riches",
  "Redemption Arc",
  "Enemies Forced to Work Together",
];
